### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by biffotmc** [ewanhowell5195/customOptiFineCapeServer#11]
It doesnt work for me the capes dont show up and when i go to s.optifine.net or 127.0.0.1 it puts this error in the console
![image](https://user-images.githubusercontent.com/86079175/124965851-7a444c80-e01a-11eb-8bb2-2d18a3c22e59.png)
also is there anyway that i could build the program myself?

**Comment by ewanhowell5195** [comment]
what happens when you go to `http://s.optifine.net/capes/ewanhowell5195.png`

**Comment by biffotmc** [comment]
![ewanhowell5195](https://user-images.githubusercontent.com/86079175/125111238-91983e00-e0dd-11eb-9cd4-7e56e2b64788.png)
and also
![image](https://user-images.githubusercontent.com/86079175/125111280-9fe65a00-e0dd-11eb-8f91-12865f7f1499.png)

**Comment by ewanhowell5195** [comment]
It’s working fine then

**Comment by biffotmc** [comment]
but the cape doesnt show up in game
and im using optifine

**Comment by ewanhowell5195** [comment]
1. Are you using OptiFine
2. Are you closing the console

**Comment by biffotmc** [comment]
1. Yes
2. No

**Comment by Roseeees** [comment]
And if I start the server and my friend write ip s.optifine.net in the host file he will see his cloak?

**Comment by ewanhowell5195** [comment]
no he needs to run the program

**Comment by Roseeees** [comment]
there are analogues by type cloacs+ I want to do how do they do it?

**Comment by Roseeees** [comment]
and how to change the IP address?
