### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by Roseeees** [ewanhowell5195/customOptiFineCapeServer#14]
I have a question maybe you better record a video and show all the details? it's just that I'm from Russia and I don't really understand English :(

**Comment by Roseeees** [comment]
why are you closing everything?

**Comment by ewanhowell5195** [comment]
because you keep opening new issues

**Comment by Roseeees** [comment]
Beg your pardon

**Comment by Roseeees** [comment]
You can record a video instruction on this topic I can not + as I said I am from Russia

**Comment by Roseeees** [comment]
I can't install according to the instructions

**Comment by Roseeees** [comment]
I did everything but it didn't work out

**Comment by ewanhowell5195** [comment]
im not recording a video. you will have to translate it

**Comment by Roseeees** [comment]
translator does not always work

**Comment by Roseeees** [comment]
sorry but what does the ipconfig /flushdns command do in cmd

**Comment by ewanhowell5195** [comment]
flush the dns

**Comment by Roseeees** [comment]
why do that? what's the point of it doing to harm my computer?

**Comment by ewanhowell5195** [comment]
it doesnt harm your computer. it just means you dont need to restart it

**Comment by Roseeees** [comment]
and then make it so that my friend writes ip aders in the host and gets a cloak of the besch program because if in cloak+ so do then you will have a cloak and does the cloaks work on non-licenses?

**Comment by Roseeees** [comment]
how do I shut down the server?

**Comment by ewanhowell5195** [comment]
if you want to see the capes, you need the program. this is different to cloaks+.

if you turn off the server, it wont work

**Comment by Roseeees** [comment]
do you know cloak+?

**Comment by Roseeees** [comment]
if yes then how they give optifain cloaks

**Comment by ewanhowell5195** [comment]
if you dont like how this works, use cloaks+ instead

**Comment by ewanhowell5195** [comment]
you cant do the same with this.

**Comment by Roseeees** [comment]
like cloac+

**Comment by Roseeees** [comment]
why can't I see my cloak? I did everything according to the instructions

**Comment by Roseeees** [comment]
it works on Tlauncher?

**Comment by ewanhowell5195** [comment]
buy the game. i will not discuss this futher
