### ISSUE TITLE
Typo error dafault to default

### ISSUE THREAD

**Issue by r-rajaneesh** [ewanhowell5195/customOptiFineCapeServer#4]
##Typo error dafault to default

![Error](https://user-images.githubusercontent.com/75080457/108953309-fef88480-7690-11eb-9980-2eb14b0fa96c.png)

to

![Fixed Error](https://user-images.githubusercontent.com/75080457/108953342-0d46a080-7691-11eb-861d-0718ec073c1e.png)

[##settings.jon in a zip file](https://github.com/ewanhowell5195/customOptiFineCapeServer/files/6033628/settings.zip)

**Comment by ewanhowell5195** [comment]
fixed
