### ISSUE TITLE
"This app can't run on your PC"

### ISSUE THREAD

**Issue by d-prob** [ewanhowell5195/customOptiFineCapeServer#5]
might as well put this here

![image](https://user-images.githubusercontent.com/57526976/109373617-e71c3d00-78ea-11eb-8e2b-462593750751.png)

I definitely do not have any further explanation than this

**Comment by d-prob** [comment]
ok i think i found one; avg thinks it is a trojan virus

**Comment by ewanhowell5195** [comment]
the only fix is whitelisting it in AVG then.
