### ISSUE TITLE
[BUG] File Missing

### ISSUE THREAD

**Issue by r-rajaneesh** [ewanhowell5195/customOptiFineCapeServer#8]
`<api-ms-win-core-path-l1-1-0.dll>` is missing from your computer

Where can I Find/Get this file?? 

@<ewanhowell5195#8042>

@ewanhowell5195

**Comment by ewanhowell5195** [comment]
You find it by updating windows.

**Comment by r-rajaneesh** [comment]
> You find it by updating windows.

which OS do you mean?

**Comment by ewanhowell5195** [comment]
Not windows 7
